### ISSUE TITLE
Cleanup repo readme and github org

### ISSUE THREAD

**Issue by BigLep** [libp2p/js-http-v1-content-routing#23]
A couple of organizational ideas:
1. The readme mentions reframe.  Lets update that.
2. HTTP /routing/v1 is more of an IPFS concept rather than a libp2p one (i.e., it's specified under specs.ipfs.tech).  As a result, lets put this in the ipfs org/namespace?

**Comment by BigLep** [comment]
@achingbrain : can this repo just be closed because it is replaced by https://github.com/ipfs/helia-routing-v1-http-api ?  If so, lets deprecate npm and point everything to https://github.com/ipfs/helia-routing-v1-http-api

**Comment by BigLep** [comment]
Some of this cleanup happened in https://github.com/libp2p/js-delegated-routing-v1-http-api-content-routing/pull/27

**Comment by achingbrain** [comment]
https://github.com/ipfs/helia-delegated-routing-v1-http-api/pull/44 allows use of the delegated routing v1 http api client as a libp2p service (which detects ContentRouting and PeerRouting capabilities) which would render this module obsolete.

**Comment by achingbrain** [comment]
Fixed in https://github.com/libp2p/js-delegated-routing-v1-http-api-content-routing/commit/c4aa825797d8abfeba38b8d255e24abea40ceb9c
