### ISSUE TITLE
Support IPIP-379 (Delegated IPNS lookups)

### ISSUE THREAD

**Issue by BigLep** [libp2p/js-http-v1-content-routing#24]
## Done Criteria
[IPIP-379 (Delegated IPNS lookups)](https://specs.ipfs.tech/ipips/ipip-0379/) support, meaning could delegate IPNS lookups with another HTTP /routing/v1 implementation like Kubo

## Why Important
This is needed for the Helia reliable retrieval golden path scenario: https://github.com/ipfs/helia/issues/255

**Comment by achingbrain** [comment]
Fixed in #27
